name: Sync fork

permissions:
  contents: write

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  sync:
    name: Sync fork
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Ensure we fetch all branches and history
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote
        run: git remote add upstream https://github.com/ORIGINAL_OWNER/ORIGINAL_REPOSITORY.git

      - name: Fetch upstream
        run: git fetch upstream

      - name: Merge upstream changes
        run: git merge upstream/main
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push changes
        run: git push origin main
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: gautamkrishnar/keepalive-workflow@v1
